name: PanelCraft
version: '${project.version}'
main: club.smartsheep.panelcraftcore.PanelCraft
api-version: 1.13
softdepend: [PlaceholderAPI, Vault, ProtocolLib]
commands:
  refreshpanelrootpassword:
    permission: op
    permission-message: §cYou do not have enough permission to perform this command
    usage: §c/refreshpanelrootpassword Refresh the PanelCraft root password